//! Example of Station Mode Monitor for CSI Collection
//!
//! This configuration connects to an Access Point and monitors for stimulus traffic generated by an Access Point Trigger or AP/STA Trigger.
//! This configuration collects locally stimulated CSI data and sends it back to the trigger source in a UDP message.
//!
//! At least two ESP devices (one Station Monitor and one Access Point Trigger) are needed to enable this configuration.
//!
//! Connection Options:
//! - Option 1: Connect to Access Point Trigger
//! - Option 2: Connect to AP/STA Trigger
//!
//! Option 2 would support capturing NTP data in case the Access Point Trigger or AP/STA Trigger has internet connectivity.
//!
#![no_std]
#![no_main]

use embassy_executor::Spawner;
use embassy_time::{Duration, Timer};
use esp_bootloader_esp_idf::esp_app_desc;
use esp_csi_rs::{
    collector::{CSIStation, StaMonitorConfig, StaOperationMode},
    config::CSIConfig,
};
use esp_hal::rng::Rng;
use esp_hal::timer::timg::TimerGroup;
use esp_println as _;
use esp_println::println;
use esp_wifi::{init, wifi::ClientConfiguration, EspWifiController};

use embassy_time::with_timeout;

esp_app_desc!();

extern crate alloc;

macro_rules! mk_static {
    ($t:ty,$val:expr) => {{
        static STATIC_CELL: static_cell::StaticCell<$t> = static_cell::StaticCell::new();
        #[deny(unused_attributes)]
        let x = STATIC_CELL.uninit().write(($val));
        x
    }};
}

#[esp_hal_embassy::main]
async fn main(spawner: Spawner) {
    // Configure System Clock
    let config = esp_hal::Config::default().with_cpu_clock(esp_hal::clock::CpuClock::max());
    // Take Peripherals
    let peripherals = esp_hal::init(config);

    // Allocate some heap space
    esp_alloc::heap_allocator!(size: 128 * 1024);

    println!("Embassy Init");
    // Initialize Embassy
    let timg1 = TimerGroup::new(peripherals.TIMG1);
    esp_hal_embassy::init(timg1.timer0);

    // Instantiate peripherals necessary to set up  WiFi
    let timer1 = esp_hal::timer::timg::TimerGroup::new(peripherals.TIMG0);
    let wifi = peripherals.WIFI;
    let timer = timer1.timer0;
    let rng = Rng::new(peripherals.RNG);

    println!("Controller Init");
    // Initialize WiFi Controller

    let init = &*mk_static!(EspWifiController<'static>, init(timer, rng).unwrap());

    // Instantiate WiFi controller and interfaces
    let (controller, interfaces) = esp_wifi::wifi::new(&init, wifi).unwrap();

    println!("WiFi Controller Initialized");

    // Create a CSI collector statiom configuration to monitor for external traffic
    let mut csi_coll_sta = CSIStation::new(
        CSIConfig::default(),
        ClientConfiguration {
            ssid: "esp".into(),
            password: "12345678".into(),
            auth_method: esp_wifi::wifi::AuthMethod::WPA2Personal,
            channel: Some(1),
            ..Default::default()
        },
        // Configure the STA to Monitor Mode
        // Config defaults to 10789 for both local and destination ports
        StaOperationMode::Monitor(StaMonitorConfig::default()),
        // Set to true only if there is an internet connection at AP
        false,
        // Pass the controller instance
        controller,
    )
    .await;

    // Initalize CSI collector
    csi_coll_sta.init(interfaces, &spawner).await.unwrap();

    // Start Collection
    csi_coll_sta.start_collection().await;

    // Collect/Monitor for 10 Seconds
    Timer::after(Duration::from_secs(10)).await;

    // Stop Collection & capture controller
    csi_coll_sta.stop_collection().await;

    println!("Starting Again in 3 seconds");
    Timer::after(Duration::from_secs(3)).await;

    // Start Collection Again
    csi_coll_sta.start_collection().await;

    // Collect for 5 Seconds
    Timer::after(Duration::from_secs(5)).await;

    // Stop Collection
    csi_coll_sta.stop_collection().await;

    loop {
        Timer::after(Duration::from_secs(1)).await
    }
}
